### ISSUE TITLE
OS X - Unable to view alternate parse trees

### ISSUE THREAD

**Issue by NotNormal** [antlr/intellij-plugin-v4#309]
When debugging a grammar on IntelliJ for OS X: I would like to also be able to view the alternate parse trees for ambiguous grammars. Currently, when I find an ambiguity and right-click on the offending phrase: I'm offered the option to paste from my clipboard and there is no option to 'Show all phrase interpretations'.
![screen shot 2017-05-17 at 1 36 02 pm](https://cloud.githubusercontent.com/assets/2340488/26167793/d3d90cfe-3b05-11e7-831c-eaad26b18dca.png)

**Comment by sfackler** [comment]
This appears to be broken on Windows 10 as well.

**Comment by parrt** [comment]
whoa. this is weird and likely an issue with 2018.2 version previous generations. @bjansen can you take a look?

**Comment by bjansen** [comment]
I believe it's been broken for quite some time, possibly because of [this commit](https://github.com/JetBrains/intellij-community/commit/589929b61b6ffed0c2fe30f1361b41584ccf17ba).

What's happening is that the Editor we create is assigned a default "context menu group id", and for every mouse click, a listener is called *before* the one added by our plugin. This listener will try to see if there are default actions registered under this "context menu group id", if so it creates the corresponding context menu, then "consumes" the event. Because the event is consumed, the following mouse listeners won't be called.

Unfortunately, copy/pase actions are registered under the default "BasicEditorPopupMenu" context menu group id, that's why the paste action is showned instead of our own action.

I'm working on a PR to fix that.
