### ISSUE TITLE
"can't find or load grammar" for imported grammars.

### ISSUE THREAD

**Issue by StochasticTinkr** [antlr/intellij-plugin-v4#383]
I have  Expressions.g4 in src/main/antlr4/imports/
I have Struct.g4 in src/main/antlr4/com/example

Struct.g4 imports Expressions.g4

I have configured the "Location of imported grammars"  correctly.  If I didn't, then the editor pane would show errors.

The Tool Output pane shows

> error(110): /path/to/src/main/antlr4/com/example/Struct.g4:3:7: can't find or load grammar Expressions

This affects the preview ability, but not the syntax highlighting/ error reporting in the .g4 file.

**Comment by martypitt** [comment]
I have the same issue

**Comment by zenja** [comment]
same issue here.

**Comment by roggenbrot** [comment]
I have the same problem. 
Reason for the problem is that the lib directory for [org.antlr.v4.Tool](https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/Tool.java#L105) is not set to the configured `location of imported grammars`

Since the path is not set, the imports will be always searched in wrong path (Resolution order:  `inputDirectory`, path of grammar file, `libDirectory`)


I will create a pull request which sets `libDirectory` to the configured path

**Comment by bjansen** [comment]
Thanks @roggenbrot!
