### ISSUE TITLE
Add "pin" feature to ANTLR Preview

### ISSUE THREAD

**Issue by erichsilvestre** [antlr/intellij-plugin-v4#409]
After starting a preview then opening a file other than the current grammar file, the preview window is disabled.

Many times we want to change source code meanwhile seeing the parser tree preview. It would be very useful to have a 'pin' feature that once enabled would stick the preview to the current selected grammar file and start rule.
It would continue to display that preview instead of updating it according to further file selections.

**Comment by bjansen** [comment]
Hi,

Thanks a lot for the feedback. This is an area in which I think we could make things better. I believe the reasoning for the current behavior implemented by @parrt is as follows:

* the tool window content is tied to a specific grammar
* this means that when you switch from a grammar to another grammar, the content is updated/restored accordingly
* this also means that when you switch to a non grammar file, the tool window is not "relevant" anymore, so it's disabled and hidden

Yet this behavior does not feel "natural", compared to all the other tool windows, especially the hiding part.

I can think of two alternative behaviors:
* each grammar has its own tab in the tool window. The user decides when they want to switch from one tab to another, navigating to another grammar will not affect this window.
* instead of a tool window, split the editor to show the grammar at the top, and the preview on the bottom (like the Grammar-Kit plugin does). The preview part will likely become bigger than the current tool window (half the editor size), so that could be a good thing I guess.

Opinions are welcome :)

**Comment by parrt** [comment]
Yep, i was trying to keep things consistent as I bounced from grammar to grammar.  Inline with that approach, your 2nd suggestion might be best. Which is easier to implement?

**Comment by bjansen** [comment]
I guess option 1 requires less work, but on the other hand we could implement option 2 like the Grammar-Kit plugin does. I think the hardest part is to refactor `ANTLRController` which currently acts as a singleton (because we're only working on 1 preview at a time).

**Comment by parrt** [comment]
Well, you are providing free expertise/coding so I think it's up to you.  Most people only work on one grammar at a time so I wonder just how common this requirement is to handle multiple. @erichsilvestre is actually just asking us to keep the parse tree alive. maybe that is a simpler requirement?

**Comment by bjansen** [comment]
Right, since I have limited time to work on this project, maybe it's best that I keep it simple. If most people work on one grammar, maybe we could do this:

* the preview is initially disabled (this is the current behavior)
* when the user tests a parser rule, the preview becomes available (also the current behavior)
* when the user switches to another file, we keep the preview enabled, and we don't minimize the window (unlike the current version does)
* when the user switches to another grammar, we keep the preview as-is until they test a different parser rule

=> the preview remains visible and untouched unless a different parser rule is tested.

Now we have two options: either this becomes the default (and only) behavior, or we implement it as a 'pin' feature like @erichsilvestre suggested

**Comment by parrt** [comment]
i like the suggestion a lot. hmm...maybe make it the default behavior

**Comment by erichsilvestre** [comment]
Any luck with the implementation? As we use your plugin very often, I am willing to implement it and create a MR, how does it sound to you?

**Comment by bjansen** [comment]
Haven't had time to work on it, sorry. Contributions are welcome :)

**Comment by parrt** [comment]
Hmm...reading this again, what if we keep the preview open ONLY if they switch to non-grammar file? Let me check the PR.
