### ISSUE TITLE
Issues with whitespaces within doublequote enclosed strings being parsed with dots

### ISSUE THREAD

**Issue by iohelder** [antlr/intellij-plugin-v4#412]
I want to print strings enclosed in double quotes, with whitespace. Seems like Intellij's ANTLR4 plugin generates trees showing dots instead of spaces.

The behavior is different in VSCode's plugin where the whitespaces are displayed in the parsed tree. Is it a bug or was it designed that way?

An example of a test grammar:

```
grammar strings;

prule: expr* EOF;  // parser rule
expr: ID ASSIGN type SEMICOLON;
type: STRING;

ASSIGN: '=';
SEMICOLON: ';';
ID: [a-zA-Z]+;
STRING : ('"') ('a'..'z' |'A'..'Z'|' ')* ('"'); // lexical rule

WS: [ \n\t\r]+ -> skip;
```

If input is ```mystring = "hello world"```

```STRING``` will hold ```hello.world``` instead of ```hello world``` as one would expect. Glad to hear if there is a fix for this.

**Comment by bjansen** [comment]
The IntelliJ plugin is reusing the same tree as the one provided by `org.antlr.v4.gui.TestRig -gui` (the CLI tool) :

![image](https://user-images.githubusercontent.com/281528/94545130-6e865700-024c-11eb-9956-e0468c189d99.png)

I have no idea if this behavior can be customized, maybe @parrt knows?

**Comment by parrt** [comment]
I put the dot in there specifically to indicate how many white space.  I can't remember if there's a way to change this but you can take a look at the tree layout stuff.

**Comment by bjansen** [comment]
To answer your original question, it is by design.

See https://github.com/antlr/antlr4/blob/9e64dfc6e99f7dcf7cae492927d37290daf57734/tool/src/org/antlr/v4/gui/TreeViewer.java#L684 and https://github.com/antlr/antlr4/blob/9e64dfc6e99f7dcf7cae492927d37290daf57734/runtime/Java/src/org/antlr/v4/runtime/misc/Utils.java#L64

I guess we could override `getText()` in our own subclass, if that's something you really want.

**Comment by parrt** [comment]
I'm not sure how often this problem comes up.  To clean up, I'll close as I doubt I'll be able to priority this feature.
