### ISSUE TITLE
Token Visualisation

### ISSUE THREAD

**Issue by gkjpettet** [antlr/intellij-plugin-v4#417]
Hi,

Many thanks for this extension - it’s proving really useful when learning ANTLR.

Does the extension provide any way to see the tokens generated during lexing? I have figured out how to view the parse tree but I would really like to see the tokens generated before parsing. I'm having issues with certain tokens and I'd like to just throw the extension a large file and view the generated tokens.

Is this possible?

**Comment by bjansen** [comment]
Hi,

You can see lexer tokens in the `Hierarchy` view:

![image](https://user-images.githubusercontent.com/281528/97563568-8552d180-19e3-11eb-8818-62266ccef5db.png)

But it's not a detailed view of the whole token stream, if that's what you are looking for.

**Comment by gkjpettet** [comment]
Ah I see - you can only view the tokens matching a rule? OK, thanks.

**Comment by bjansen** [comment]
Here's a simple implementation:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/281528/105093932-c539ca00-5aa3-11eb-85e7-356cd42d5b32.png">

As you can see, it shows tokens that are not matched by any rule, like `ERR`.

Things that could be improved, depending on what would be useful for you:
* show the token name instead of its int value (at the moment it's just a `Token.toString()`)
* highlight the corresponding text in the preview editor when a token is selected in the list
* highlight the corresponding token in the list when moving the cursor in the preview editor
* show/hide tokens based on their channel? (for example if you're not interested in what's in the `HIDDEN` channel, but that might be too far-fetched).

**Comment by bjansen** [comment]
Updated version: 
<img width="845" alt="image" src="https://user-images.githubusercontent.com/281528/105612261-325aa180-5dbb-11eb-9a19-a49208fcfeee.png">
It shows token names instead of token ids, and I added global "scroll from source/scroll to source" buttons on the left toolbar, which are also used by the Hierarchy tab:
![image](https://user-images.githubusercontent.com/281528/105612342-adbc5300-5dbb-11eb-86f5-d8f3316db58c.png)


WDYT @gkjpettet and @nmz787?

**Comment by bjansen** [comment]
Will be in 1.17

**Comment by parrt** [comment]
What about just looking in input stream at token of interest and just using cmd or whatever + mouse hover? It pops up info on the token?
