### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by roggenbrot** [antlr/intellij-plugin-v4#424]
At the moment the editor seems to have no code formatter attached. Would it be possible to integrate a code formatter into the plugin?

I can try to implement this based on [AntlrFormatter](https://github.com/antlr/Antlr4Formatter) and [FormattingModelBuilder](https://jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_formatting.html) and submit a pull request.

**Comment by bjansen** [comment]
There's already #97 for code formatting, please subscribe to this issue to follow progress. I've started working on it last year, but haven't had enough time to make something mature enough. I don't know Antlr4Formatter well enough, but I'm pretty sure there is no way to make it work with IntelliJ's formatting model (especially since [IJ can format partial files](https://jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/code_formatting.html)).
