### ISSUE TITLE
Can't disable sources generation

### ISSUE THREAD

**Issue by cubuspl42** [antlr/intellij-plugin-v4#491]
Thank you for creating this plugin! Unfortunately, I have a serious productivity-affecting issue with it.

I've unchecked the "Auto-generate parsers upon save" for both the lexer definition and for the parser definition files. 

![image](https://user-images.githubusercontent.com/2590174/150684430-6fff40c8-cae0-468d-8532-7ea3b94dcd16.png)

![image](https://user-images.githubusercontent.com/2590174/150684442-1731eebf-4125-49cb-a886-a88bf14ecfe5.png)

It doesn't seem to be respected. The `gen` directory keeps appearing (just as a consequence of editing stuff in the IDE). My actual (desired) generation is configured via the Gradle plugin, things go to `generated-src` and there are some custom flags passed.

I don't want the IDE to directly take part in the source generation process. I wanted to use the plugin for the syntax highlighting, maybe some basic editing support, while it's messing with my sources. That's an aggressive default, leave alone that I can't (or don't understand how to?) disable it at all. 😞

**Comment by bjansen** [comment]
Hi,

What kind of files do you see in the `gen` directory? The plugins runs an interpreter in the Preview window, so it doesn't need the actual generated lexer/parser. It does need _some_ generated files though, namely the `.tokens` file generated from lexer grammars. In a sample project I see that `Lexer.java` and `Lexer.interp` are also generated but I don't think the plugins requires them.

@parrt do you know if there's a way to run the interpreter without generating the `.tokens` file? Maybe by creating an in-memory version of the data instead of generating a file on the FS?

**Comment by parrt** [comment]
I suppose we could tweak things the tool so that it did not generate the interpreter file but instead returned it to a caller.  I'm just now swapping antlr knowledge back into my head and am trying to get antlr 4.10 out the door, so unfortunately this will not be my focus for a little while. Perhaps @bjansen  can drive things and tell me what he needs from the tool.

@cubuspl42  I agree that it is an aggressive default. hilarious. I love that term.

**Comment by KvanTTT** [comment]
I'd just wanted to suggest disabling `Lexer.interp` file generation by default. In most applications, it's not used but takes extra memory and slows down generation a bit. But if you need interpretation, with option `--interp` you can generate such files as before.

Also, another option may be useful `--no-generate` that completely disables all generation. It's useful when you only want to check grammar errors. It also may improve the performance of ANTLR tool.

**Comment by parrt** [comment]
I think my reasoning was to reduce the options because it doesn't really take that much effort to generate that file.  Reducing options also reduces the test search space.

**Comment by cubuspl42** [comment]
@bjansen 

> What kind of files do you see in the `gen` directory?

* `BiaLexer.interp`
* `BiaLexer.java`
* `BiaLexer.tokens`

...so "all of them", I guess.

**Comment by parrt** [comment]
I have everything turned off in configuration for a fairly large grammar:

<img width="697" alt="Screen Shot 2022-02-27 at 11 54 20 AM" src="https://user-images.githubusercontent.com/178777/155897631-6f88a55e-f750-4ef4-8105-9d005d80d62d.png">

and unless I say "generate recognizer" I don't get any output in `gen` nor does it create that directory. this is using 1.17 plug-in and community edition 2021.2 intellij.

It does not appear that you needed to do any preview which *might* trigger generation, but I don't see it generating files even when I do a preview and give it some input text to parse.

**Comment by cubuspl42** [comment]
I'll see if unchecking the two bottom checkboxes help, as in my case I have them checked.

**Comment by bjansen** [comment]
@parrt I can see those files are generated when I test a rule on a "split grammar" (XLexer.g4 + XParser.g4). It's not related to the "Generate" action.

**Comment by parrt** [comment]
When we have a split grammar, I have a note in the code that when I switch from a lexer to the parser, I regenerate the `.tokens` file because that could be needed by the parser. But, I don't think that goes in there `gen` dir. It goes in the directory containing the grammar.  Would that be an issue for you @cubuspl42 ?

**Comment by cubuspl42** [comment]
Sorry, I've recently moved away from my ANTLR-related project. I hope I'll go back to it at some point. When I do, I'll do more testing and investigation related to that mysterious `gen` directory. For now we can close this.

**Comment by parrt** [comment]
No problem. thanks!

**Comment by ty1824** [comment]
I have noticed the same issue. I am working on a project (several developers working on it) and we have configured the antlr generation from gradle.

The antlr plugin is useful as it provides a better editing experience and the tools are handy, but I don't see a way to share the configuration (disabling generation) between developers. This is a red flag for me as we're trying to have reproducible environments.

I can help by providing more information about our configuration and such (I also have an open source project with a similar configuration), can we reopen this?

Or I can open a new issue if that is preferred.
