### ISSUE TITLE
CMD-Click on grammar definition does not go to usages in 1.18 or later

### ISSUE THREAD

**Issue by wfahle** [antlr/intellij-plugin-v4#580]
In 1.17, CMD-click on a grammar usage would go to the definition, and CMD-click on the definition would show usages (like Edit/Find Usages/Show Usages does). In version 1.18 or later, CMD-click on a grammar usage still jumps to the definition, but CMD-click on the definition just jumps to the beginning of the line. Rather useless by comparison.

**Comment by TysonMN** [comment]
Here is what I found after looking at the commits between 1.17 and 1.18.

Commit https://github.com/antlr/intellij-plugin-v4/commit/8ae7cbd64e52915bb65e638c5320c17c0c2c759e changed the leaf node `GrammarElementRefNode` to implement `PsiNamedElement`, which is not correct (c.f. https://github.com/antlr/jetbrains-plugin-sample/issues/17).

Commit c16d5b123cf7dd183e63468f8901c5647fa3cb67 changed tests for "Find Usages".  Maybe this change to test code would not be needed if the previous commit had not introduced a mistake.

I don't see anything else, so my guess is that the fix is to change `GrammarElementRefNode` to not implement `PsiNamedElement` (again).

**Comment by bjansen** [comment]
>Commit https://github.com/antlr/intellij-plugin-v4/commit/8ae7cbd64e52915bb65e638c5320c17c0c2c759e changed the leaf node GrammarElementRefNode to implement PsiNamedElement, which is not correct (c.f. https://github.com/antlr/jetbrains-plugin-sample/issues/17).

It looks like it's _half_ correct. For example, `TOKEN_REF` is used both in `lexerRule` (name declaration) and in `identifier` (name reference). As a result, `GrammarElementRefNode` should implement `PsiNamedElement` in one case but not the other. I think we'll have to split `TOKEN_REF` into `TOKEN_DEF` and `TOKEN_REF`, then make `GrammarElement**D**efNode` implement `PsiNamedElement` but not `GrammarElement**R**efNode`.

**Comment by bjansen** [comment]
Thanks for the detailed analysis here and in jetbrains-plugin-sample by the way!

**Comment by TysonMN** [comment]
You're welcome for the analysis.  However, it was my pleasure.  We are using ANTLR for three custom languages at work.  We just created an IntelliJ plugin for two of them, and the [ANTRL4 IntelliJ adaptor](https://github.com/antlr/antlr4-intellij-adaptor) makes it very easy, so it is the least I could do in return.

**Comment by wfahle** [comment]
Thanks for the analysis! I will take a look and see if I can implement and
test those changes. I have a build locally. It sounds like a rollback
mostly.

**Comment by wfahle** [comment]
I have verified that removing the implements PsiNamedElement from GrammarElementRefNode (and removing the then-unused setName method) makes this plugin work the same as the Java plugin does (i.e., it fixes this issue). However it did fail a test, maybe spuriously, in Issue540Test (test_shouldOnlyCreateTokensWhenModified). So I will not create a pull request for this issue from that, as this will require further investigation.

**Comment by bjansen** [comment]
This test also fails on my machine, but not in Actions. Did you manage to get it working?

**Comment by bjansen** [comment]
Fixed by #625
